package task_scheduler;
import java.time.Clock;
import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.ZoneOffset;
import java.time.ZonedDateTime;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {
//    	Clock testClock = Clock.fixed(Instant.EPOCH, ZoneOffset.UTC);
//    	LocalDate testDate = LocalDate.now(testClock);
//    	
//    	Calendar calendar = new Calendar();
//    	
//    	calendar.addTask(1, 0, "Answer an urgent e-mail");
//    	calendar.addTask(1, 0, "Write deployment report");
//    	calendar.addTask(1, 0, "Plan security configuration");
//    	
//    	// add some work periods to the calendar
//    	calendar.addWorkPeriods(Utils.generateWorkPeriods(testDate, 3));
//    	
//    	
//    	// add an event to the calendar, specifiting its time zone
//    	ZonedDateTime meetingTime = ZonedDateTime.of(testDate.atTime(8, 30) , ZoneId.of(("America/New_York")));
//    	Schedule schedule = calendar.createSchedule();
    }
}
